2018-11-19 17:30:34 ERROR (MainThread) [homeassistant.setup] Setup failed for mqtt: Component failed to initialize.
2018-11-19 17:30:34 ERROR (MainThread) [homeassistant.setup] Unable to set up dependencies of sensor.mqtt. Setup failed for dependencies: mqtt
2018-11-19 17:30:34 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform sensor.mqtt: Could not set up all dependencies.
2018-11-19 17:30:34 ERROR (MainThread) [homeassistant.setup] Unable to set up dependencies of sensor.mqtt. Setup failed for dependencies: mqtt
2018-11-19 17:30:34 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform sensor.mqtt: Could not set up all dependencies.
2018-11-19 17:30:34 ERROR (MainThread) [homeassistant.setup] Unable to set up dependencies of sensor.mqtt. Setup failed for dependencies: mqtt
2018-11-19 17:30:34 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform sensor.mqtt: Could not set up all dependencies.
2018-11-19 17:30:34 ERROR (MainThread) [homeassistant.setup] Unable to set up dependencies of sensor.mqtt. Setup failed for dependencies: mqtt
2018-11-19 17:30:34 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform sensor.mqtt: Could not set up all dependencies.
2018-11-19 17:30:34 ERROR (MainThread) [homeassistant.setup] Unable to set up dependencies of switch.mqtt. Setup failed for dependencies: mqtt
2018-11-19 17:30:34 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform switch.mqtt: Could not set up all dependencies.
2018-11-19 17:30:34 ERROR (MainThread) [homeassistant.setup] Unable to set up dependencies of switch.mqtt. Setup failed for dependencies: mqtt
2018-11-19 17:30:34 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform switch.mqtt: Could not set up all dependencies.
2018-11-19 17:30:34 ERROR (MainThread) [homeassistant.setup] Unable to set up dependencies of switch.mqtt. Setup failed for dependencies: mqtt
2018-11-19 17:30:34 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform switch.mqtt: Could not set up all dependencies.
2018-11-19 17:30:34 ERROR (MainThread) [homeassistant.setup] Unable to set up dependencies of switch.mqtt. Setup failed for dependencies: mqtt
2018-11-19 17:30:34 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform switch.mqtt: Could not set up all dependencies.
2018-11-19 17:30:34 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry OnHub for upnp
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/config_entries.py", line 244, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/usr/src/app/homeassistant/components/upnp/__init__.py", line 143, in async_setup_entry
    await device.async_add_port_mappings(ports, local_ip)
  File "/usr/src/app/homeassistant/components/upnp/device.py", line 66, in async_add_port_mappings
    internal_port)
  File "/usr/src/app/homeassistant/components/upnp/device.py", line 87, in _async_add_port_mapping
    lease_duration=None)
  File "/usr/local/lib/python3.6/site-packages/async_upnp_client/igd.py", line 219, in async_add_port_mapping
    await action.async_call(
AttributeError: 'NoneType' object has no attribute 'async_call'
2018-11-19 17:30:34 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry OnHub for upnp
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/config_entries.py", line 244, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/usr/src/app/homeassistant/components/upnp/__init__.py", line 143, in async_setup_entry
    await device.async_add_port_mappings(ports, local_ip)
  File "/usr/src/app/homeassistant/components/upnp/device.py", line 66, in async_add_port_mappings
    internal_port)
  File "/usr/src/app/homeassistant/components/upnp/device.py", line 87, in _async_add_port_mapping
    lease_duration=None)
  File "/usr/local/lib/python3.6/site-packages/async_upnp_client/igd.py", line 219, in async_add_port_mapping
    await action.async_call(
AttributeError: 'NoneType' object has no attribute 'async_call'
2018-11-19 17:30:37 ERROR (SyncWorker_19) [homeassistant.components.light.yeelight] Failed to connect to bulb 192.168.87.56, Family Room Lamp: A socket error occurred when sending the command.
